name: Build Kriware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip and Prepare
        run: |
          # Создаем временную папку и распаковываем туда всё
          mkdir temp_build
          unzip -o jni.zip -d temp_build
          
          # Создаем структуру, которую хочет NDK
          mkdir jni
          # Перемещаем всё содержимое из temp_build в jni
          mv temp_build/* jni/
          
          echo "--- Проверка структуры (должна быть папка jni) ---"
          ls -F

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          # Теперь папка jni точно есть, запускаем сборку
          ndk-build

      - name: Collect and Upload
        if: success()
        run: |
          mkdir -p final_output
          # Ищем готовые .so файлы в созданной папке libs
          find libs/ -name "*.so" -exec cp {} final_output/ \;
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Kriware_Fixed_Build
          path: final_output/        uses: actions/upload-artifact@v4
        with:
          name: Kriware_Fixed
          path: final_output/
